<?php

namespace Fulbis\Domain\Entity;

interface VersionableInterface {

    /**
     * Set autogenerated ID
     *
     * @param $id
     * @return mixed
     */
    public function setIdAuto($id);

    /**
     * Get UUID
     *
     * @return mixed
     */
    public function getId();

    /**
     * Set deleted value
     *
     * @param $deleted
     * @return mixed
     */
    public function setDeleted($deleted);

}